import { getSupabaseClient } from '$lib/database/supabaseClient';
import { get } from 'svelte/store';
import { selectedBranch } from "$lib/stores/selectedBranch";
import { checkRateLimit } from './validation.js';
import { browser } from '$app/environment';
import { isAuthenticated, getCurrentUser } from '$lib/auth/auth';

// Security middleware untuk proteksi rute
export class SecurityMiddleware {
  private static _csrfToken: string | null = null;
  // Check authentication untuk protected routes
  static async requireAuth(): Promise<boolean> {
    if (!browser) return true;
    if (!isAuthenticated()) {
      window.location.href = '/login';
      return false;
    }
    return true;
  }

  // Check role-based access
  static async requireRole(requiredRole: string): Promise<boolean> {
    const ok = await this.requireAuth();
    if (!ok) return false;
    const user = getCurrentUser();
    if (!user || user.role !== requiredRole) {
      window.location.href = '/unauthorized';
      return false;
    }
    return true;
  }

  // Check admin access
  static async requireAdmin(): Promise<boolean> {
    return await this.requireRole('admin');
  }

  // Check kasir access
  static async requireKasir(): Promise<boolean> {
    return await this.requireRole('kasir');
  }

  // Rate limiting untuk API calls
  static checkApiRateLimit(userId: string): boolean {
    return checkRateLimit(`api_${userId}`, 100, 60000); // 100 requests per minute
  }

  // Rate limiting untuk form submissions
  static checkFormRateLimit(userId: string): boolean {
    return checkRateLimit(`form_${userId}`, 10, 60000); // 10 submissions per minute
  }

  // Validate CSRF token (client-side for now, server-side validation is crucial in production)
  static validateCSRFToken(token: string): boolean {
    // In a real production environment, this token would be generated by the server
    // and validated against a server-side session or a secure mechanism.
    // This client-side check is a basic placeholder.
    return !!token && token === SecurityMiddleware._csrfToken;
  }

  // Generate CSRF token (client-side for now, server-side generation is crucial in production)
  static generateCSRFToken(): string {
    if (!SecurityMiddleware._csrfToken) {
      SecurityMiddleware._csrfToken = 'csrf_' + Math.random().toString(36).substring(2) + Date.now().toString(36);
    }
    return SecurityMiddleware._csrfToken;
  }

  // Sanitize data sebelum disimpan
  static sanitizeData(data: any): any {
    if (typeof data === 'string') {
      return this.sanitizeString(data);
    }
    
    if (Array.isArray(data)) {
      return data.map(item => this.sanitizeData(item));
    }
    
    if (typeof data === 'object' && data !== null) {
      const sanitized: any = {};
      for (const [key, value] of Object.entries(data)) {
        sanitized[key] = this.sanitizeData(value);
      }
      return sanitized;
    }
    
    return data;
  }

  // Sanitize string input
  private static sanitizeString(input: string): string {
    if (typeof input !== 'string') return '';
    
    return input
      .trim()
      .replace(/[<>]/g, '') // Remove HTML tags
      .replace(/javascript:/gi, '') // Remove javascript protocol
      .replace(/on\w+=/gi, '') // Remove event handlers
      .replace(/script/gi, '') // Remove script tags
      .replace(/iframe/gi, '') // Remove iframe tags
      .replace(/data:/gi, '') // Remove data protocol
      .replace(/vbscript:/gi, ''); // Remove vbscript protocol
  }

  // Validate file upload (dummy implementation)
  static validateFileUpload(file: File): { isValid: boolean; error?: string } {
    // Check file size (max 5MB)
    if (file.size > 5 * 1024 * 1024) {
      return { isValid: false, error: 'Ukuran file maksimal 5MB' };
    }

    // Check file type
    const allowedTypes = ['image/jpeg', 'image/png', 'image/gif', 'application/pdf'];
    if (!allowedTypes.includes(file.type)) {
      return { isValid: false, error: 'Tipe file tidak diizinkan' };
    }

    return { isValid: true };
  }

  /**
   * Logs security events. In a production environment, this should send data to a secure, centralized logging service.
   * This current implementation only logs to the console (or is commented out).
   * @param event The name of the security event (e.g., 'login_failed', 'suspicious_activity_detected').
   * @param details Optional: An object containing additional details about the event.
   */
  static async logSecurityEvent(event: string, details: any = {}): Promise<void> {
    let currentUser = 'anonymous';
    if (browser) {
      try {
        const { data: { session } } = await getSupabaseClient(get(selectedBranch)).auth.getSession();
        const user = session?.user;
        if (user) {
          // Prefer username, fallback ke email, lalu id
          currentUser = user.user_metadata?.username || user.email || user.id || 'anonymous';
        }
      } catch {}
    }
    const logEntry = {
      timestamp: new Date().toISOString(),
      event,
      details,
      user: currentUser,
      ip: 'dummy-ip', // In production, get actual IP from server-side request
      userAgent: browser ? navigator.userAgent : 'server'
    };
    // console.log('SECURITY EVENT:', logEntry); // Uncomment for local debugging
    // In production, send logEntry to a logging service (e.g., Sentry, ELK Stack, custom API endpoint)
  }

  // Check for suspicious activity
  static detectSuspiciousActivity(userId: string, action: string): boolean {
    // Dummy suspicious activity detection
    const suspiciousPatterns = [
      /script/i,
      /javascript:/i,
      /<iframe/i,
      /on\w+=/i,
      /union\s+select/i,
      /drop\s+table/i,
      /delete\s+from/i
    ];

    for (const pattern of suspiciousPatterns) {
      if (pattern.test(action)) {
        this.logSecurityEvent('suspicious_activity_detected', {
          userId,
          action,
          pattern: pattern.source
        });
        return true;
      }
    }

    return false;
  }
}

// Auto-initialize security when module loads
if (browser) {
  // SecurityMiddleware.init();
} 