allowBuilds:
  '@tailwindcss/oxide': true
  core-js: true
  esbuild: true
  sharp: true
  workerd: true
overrides:
  '@esbuild-kit/core-utils>esbuild': 0.25.12
  '@humanfs/node@<0.16.8': 0.16.8
  browserslist@<=4.28.6: 4.28.7
  cookie@<0.7.0: 0.7.2
  fast-uri@<3.1.6: 3.1.6
  postcss-selector-parser@<7.1.3: 7.1.3
  serialize-javascript@<7.0.5: 7.0.5
