-- Indonesianisasi kolom domain (lanjutan). Index ikut otomatis. Kolom teknis
-- (id, *_id, created_at, updated_at, is_active, transaction_id, idempotency_key)
-- dan tabel infra tetap. Catatan: kolom `nama` (produk/bahan/kategori/tambahan)
-- dan `nominal` (buku_kas/transaksi_kasir) di kode tetap property name/amount
-- (drizzle decouple) — tapi nama KOLOM DB diseragamkan di sini.
ALTER TABLE `produk` RENAME COLUMN `name` TO `nama`;--> statement-breakpoint
ALTER TABLE `produk` RENAME COLUMN `price` TO `harga`;--> statement-breakpoint
ALTER TABLE `produk` RENAME COLUMN `track_stock` TO `lacak_stok`;--> statement-breakpoint
ALTER TABLE `produk` RENAME COLUMN `track_ingredients` TO `lacak_bahan`;--> statement-breakpoint
ALTER TABLE `bahan` RENAME COLUMN `name` TO `nama`;--> statement-breakpoint
ALTER TABLE `bahan` RENAME COLUMN `unit` TO `satuan`;--> statement-breakpoint
ALTER TABLE `bahan` RENAME COLUMN `current_stock` TO `stok_saat_ini`;--> statement-breakpoint
ALTER TABLE `bahan` RENAME COLUMN `low_stock_threshold` TO `ambang_stok`;--> statement-breakpoint
ALTER TABLE `bahan` RENAME COLUMN `cost_per_unit` TO `biaya_per_satuan`;--> statement-breakpoint
ALTER TABLE `bahan` RENAME COLUMN `last_purchase_qty` TO `jumlah_beli_terakhir`;--> statement-breakpoint
ALTER TABLE `bahan` RENAME COLUMN `last_purchase_cost` TO `biaya_beli_terakhir`;--> statement-breakpoint
ALTER TABLE `pengaturan_hpp` RENAME COLUMN `rent_monthly` TO `sewa_bulanan`;--> statement-breakpoint
ALTER TABLE `pengaturan_hpp` RENAME COLUMN `electricity_monthly` TO `listrik_bulanan`;--> statement-breakpoint
ALTER TABLE `pengaturan_hpp` RENAME COLUMN `water_monthly` TO `air_bulanan`;--> statement-breakpoint
ALTER TABLE `pengaturan_hpp` RENAME COLUMN `salary_monthly` TO `gaji_bulanan`;--> statement-breakpoint
ALTER TABLE `pengaturan_hpp` RENAME COLUMN `other_monthly` TO `lainnya_bulanan`;--> statement-breakpoint
ALTER TABLE `pengaturan_hpp` RENAME COLUMN `target_items_monthly` TO `target_item_bulanan`;--> statement-breakpoint
ALTER TABLE `resep_produk` RENAME COLUMN `qty_per_item` TO `jumlah_per_item`;--> statement-breakpoint
ALTER TABLE `bahan_mutasi` RENAME COLUMN `quantity_delta` TO `delta_jumlah`;--> statement-breakpoint
ALTER TABLE `bahan_mutasi` RENAME COLUMN `stock_after` TO `stok_setelah`;--> statement-breakpoint
ALTER TABLE `bahan_mutasi` RENAME COLUMN `source` TO `sumber`;--> statement-breakpoint
ALTER TABLE `bahan_mutasi` RENAME COLUMN `reference_id` TO `referensi_id`;--> statement-breakpoint
ALTER TABLE `bahan_mutasi` RENAME COLUMN `note` TO `catatan`;--> statement-breakpoint
ALTER TABLE `bahan_mutasi` RENAME COLUMN `created_by` TO `dibuat_oleh`;--> statement-breakpoint
ALTER TABLE `kategori` RENAME COLUMN `name` TO `nama`;--> statement-breakpoint
ALTER TABLE `kategori` RENAME COLUMN `description` TO `deskripsi`;--> statement-breakpoint
ALTER TABLE `tambahan` RENAME COLUMN `name` TO `nama`;--> statement-breakpoint
ALTER TABLE `tambahan` RENAME COLUMN `price` TO `harga`;--> statement-breakpoint
ALTER TABLE `buku_kas` RENAME COLUMN `amount` TO `nominal`;--> statement-breakpoint
ALTER TABLE `buku_kas` RENAME COLUMN `qty` TO `jumlah`;--> statement-breakpoint
ALTER TABLE `buku_kas` RENAME COLUMN `description` TO `deskripsi`;--> statement-breakpoint
ALTER TABLE `buku_kas` RENAME COLUMN `customer_name` TO `nama_pelanggan`;--> statement-breakpoint
ALTER TABLE `buku_kas` RENAME COLUMN `payment_method` TO `metode_bayar`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `qty` TO `jumlah`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `amount` TO `nominal`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `price` TO `harga`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `base_price` TO `harga_dasar`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `add_on_total` TO `total_tambahan`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `add_on_snapshot` TO `snapshot_tambahan`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `sugar` TO `gula`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `ice` TO `es`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `note` TO `catatan`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `hpp_snapshot` TO `snapshot_hpp`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `hpp_amount` TO `nominal_hpp`;--> statement-breakpoint
ALTER TABLE `transaksi_kasir` RENAME COLUMN `custom_name` TO `nama_kustom`;--> statement-breakpoint
ALTER TABLE `ringkasan_penjualan_harian` RENAME COLUMN `sales_date` TO `tanggal_penjualan`;--> statement-breakpoint
ALTER TABLE `ringkasan_penjualan_harian` RENAME COLUMN `transaction_count` TO `jumlah_transaksi`;--> statement-breakpoint
ALTER TABLE `ringkasan_penjualan_harian` RENAME COLUMN `item_count` TO `jumlah_item`;--> statement-breakpoint
ALTER TABLE `ringkasan_penjualan_harian` RENAME COLUMN `gross_sales` TO `penjualan_kotor`;--> statement-breakpoint
ALTER TABLE `ringkasan_penjualan_harian` RENAME COLUMN `cash_sales` TO `penjualan_tunai`;--> statement-breakpoint
ALTER TABLE `ringkasan_penjualan_harian` RENAME COLUMN `non_cash_sales` TO `penjualan_nontunai`;--> statement-breakpoint
ALTER TABLE `ringkasan_penjualan_harian` RENAME COLUMN `hpp_total` TO `total_hpp`;--> statement-breakpoint
ALTER TABLE `penjualan_produk_harian` RENAME COLUMN `sales_date` TO `tanggal_penjualan`;--> statement-breakpoint
ALTER TABLE `penjualan_produk_harian` RENAME COLUMN `qty` TO `jumlah`;--> statement-breakpoint
ALTER TABLE `penjualan_produk_harian` RENAME COLUMN `gross_sales` TO `penjualan_kotor`;--> statement-breakpoint
ALTER TABLE `penjualan_produk_harian` RENAME COLUMN `cash_sales` TO `penjualan_tunai`;--> statement-breakpoint
ALTER TABLE `penjualan_produk_harian` RENAME COLUMN `non_cash_sales` TO `penjualan_nontunai`;--> statement-breakpoint
ALTER TABLE `penjualan_produk_harian` RENAME COLUMN `transaction_count` TO `jumlah_transaksi`;--> statement-breakpoint
ALTER TABLE `pengaturan` RENAME COLUMN `locked_pages` TO `halaman_terkunci`;--> statement-breakpoint
ALTER TABLE `sesi_toko` RENAME COLUMN `opening_cash` TO `kas_awal`;--> statement-breakpoint
ALTER TABLE `sesi_toko` RENAME COLUMN `opening_time` TO `waktu_buka`;--> statement-breakpoint
ALTER TABLE `sesi_toko` RENAME COLUMN `closing_time` TO `waktu_tutup`;
